// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itfesulfcwoagjymqrve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0ZmVzdWxmY3dvYWdqeW1xcnZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4NTcxNzgsImV4cCI6MjA4NjQzMzE3OH0.-ygyzogFsB6Q9y0WFafdttF45tEag5kuXAlWwYe-bMQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});